ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Driver list

== GHMattiMySQL

[horizontal]
name:: `ghmattimysql`
resource:: `vrp_ghmattimysql`
project:: https://github.com/GHMatti/FiveM-MySQL

NOTE: GHMattiMySQL resource is required.

WARNING: The vRP database configuration is not supported; GHMattiMySQL configuration must be used instead.

== GHMattiMySQL (JS)

[horizontal]
name:: `ghmattimysql-js`
resource:: `vrp_ghmattimysql-js`
project:: https://github.com/GHMatti/ghmattimysql

NOTE: GHMattiMySQL resource is required.

[WARNING]
The vRP database configuration is not supported; GHMattiMySQL configuration must be used instead. +
The `multipleStatements` option must be enabled.

== oxmysql

[horizontal]
name:: `oxmysql`
resource:: `vrp_oxmysql`
project:: https://github.com/overextended/oxmysql/

NOTE: oxmysql resource is required.

[WARNING]
The vRP database configuration is not supported; oxmysql configuration must be used instead. +
The `multipleStatements` option must be enabled in the connection string (e.g., `mysql://root:password@localhost/vrp?multipleStatements=true`).
